Ajout de "mobilisable" pour le log d'un service
gip-inclusion/dora-back pull request #160
Opened 2023-08-10 14:31 UTC by AlexandreCantin

https://trello.com/c/N75MJ4BK/851-orientation-funnel-sur-plausible

2023-08-10 14:31 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Orientation - Funnel sur Plausible](https://trello.com/c/N75MJ4BK/851-orientation-funnel-sur-plausible)

2023-08-14 09:33 UTC, cedricr submitted a review, later dismissed
LGTM; seul truc: est-ce que tu penses que ce serait jouable de faire (simplement) une data-migration pour mettre à jour 'mobilisable' sur les événement existants?

2023-08-14 09:33 UTC, cedricr commented on dora/stats/models.py
> +
enlever le pass à la ligne suivante

2023-08-29 16:25 UTC, cedricr requested changes

2023-08-29 16:25 UTC, cedricr commented on dora/stats/migrations/0008_serviceview_mobilisable.py
> +        service.mobilisable = is_mobilisable(service)
hum, c'est pas le service qu'il faut modifier, c'est le serviceview...

2023-08-29 16:30 UTC, cedricr requested changes

2023-08-29 16:30 UTC, cedricr commented on dora/stats/views.py
> +    service_mobilisable = request.data.get("mobilisable", "")
```suggestion
    service_mobilisable = request.data.get("mobilisable", "") in TRUTHY_VALUES
```
ça te donne directement un booleen que tu peux utiliser tel quel l. 107, et ça évite que qqun passe "0" et que ça soit interprété comme true...

2023-08-29 16:39 UTC, cedricr commented
Voir le commentaire sur la PR front, je me demande si on ne devrait pas en faire plus en back et moins en front...

2023-09-06 13:28 UTC, merged