Save search in profile
gip-inclusion/dora-back pull request #173
Opened 2023-09-11 14:24 UTC by AlexandreCantin

2023-09-25 09:14 UTC, cedricr requested changes

2023-09-25 09:14 UTC, cedricr commented on dora/services/tests/test_services.py
> +class ServiceSavedSearchTestCase(APITestCase):
Fais-en plutôt un fichier à part, celui-ci commence à devenir beaucoup trop gros!

2023-09-25 09:14 UTC, cedricr commented on dora/services/views.py
> +            saved_search.categories.set(categories)
je ne pense pas que tes `.values_list` soient nécessaires ici, à vérifier!

2023-09-25 09:14 UTC, cedricr commented on dora/services/views.py
> +            return Response(status=400)
c'est une erreur de droits, pas une 'bad requests'

2023-09-25 09:14 UTC, cedricr commented on dora/services/views.py
> +    def save_search(self, request):
Je comprends pas ce que ça vient faire là... Il faut que tu créé un viewset dédié.

2023-09-25 09:14 UTC, cedricr commented on tools/send_saved_searchs_notifications.sh
> +  echo "L'envoi des courriels des alertes sur les recherches sauvegardées ne se fait qu'en production"
```suggestion
  echo "L'envoi des courriels de notification pour les recherches sauvegardées ne se fait qu'en production"
```
nit: seulement pour être consistents sur la terminologie

2023-09-25 09:14 UTC, cedricr commented on dora/services/models.py
> +    frequency = models.ForeignKey(
comme dit ailleurs, pas besoin d'une valeur en DB pour ça, mais 2 alternatives selon l'évolution métier prévue:
- soit on garde seulement un entier, qui correspond au nombre de jours, et c'est le front qui proposera 0 14 ou 30
- soit on propose déjà les valeurs ici, et tu en fais un choicefield, mais je ne vois pas trop la valeur ajoutée.
(le seul avantage d'avoir 'month' plutot que 30 c'est qu'on pourrait faire un vrai intervalle mensuel qui tombe toujours le même jour du mois, mais ici je ne vois pas trop l'intérêt)

2023-09-28 14:38 UTC, cedricr commented on dora/orientations/templates/contact-beneficiary.mjml
> +    <mj-image src="{{ homepage_url }}/emails/illu-orientation.png" alt=""/>
Alors non, plutôt que de le répeter à chaque fois, tu gardes un email-base.mjml dans orientations/templates, qui va hériter du email-base.mjml de core/templates, en surchargeant seulement ça.

2023-09-28 14:38 UTC, cedricr commented on dora/services/models.py
>          verbose_name="Thématiques",
```suggestion
        verbose_name="Thématique",
```

2023-09-28 14:38 UTC, cedricr commented on dora/service_suggestions/views.py
> +class ServiceSuggestionViewSet(viewsets.GenericViewSet):
Pourquoi?

2023-09-28 14:38 UTC, cedricr commented on dora/services/models.py
> +    frequency = models.ForeignKey(
Pourquoi tu n'es pas parti sur l'entier du coup? Je ne suis pas opposé à la liste hardcodée, mais je ne vois pas ce qu'elle apporte.

2023-09-28 15:35 UTC, cedricr requested changes
On y est presque!

2023-09-28 15:35 UTC, cedricr commented on cron.json
> +      "command": "30 8 * * * tools/send_saved_searchs_notifications.sh",
```suggestion
      "command": "30 7 * * * tools/send_saved_searchs_notifications.sh",
```
7 c'est mieux, ça fait 8 ou 9h en heure locale.

2023-09-28 15:35 UTC, cedricr commented on dora/services/management/commands/send_saved_searchs_notifications.py
> +                None,
c'est un peu risqué, et c'est le problème de réutiliser un sérialiser qui n'est pas fait pour ça, mais bon, ça évite une refacto assez poussé de la recherche (qui sera nécessaire un jour ou l'autre de toute façon). Alors ok, tentons le coup…

2023-09-28 15:35 UTC, cedricr commented on dora/services/management/commands/send_saved_searchs_notifications.py
> +                if datetime.fromisoformat(r["modification_date"]).date()
publication_date plutôt non? Et si c'est bien une erreur, ta couverture de tests est incomplète

2023-09-28 15:35 UTC, cedricr commented on dora/services/models.py
> +class SavedSearch(models.Model):
ça peut valoir le coup de les lister dans l'admin (dans l'objet User en tout cas)

2023-09-28 15:35 UTC, cedricr commented on dora/services/views.py
> +        serializer.save(user=self.request.user)
du coup c'est SavedSearchSerializer, et pas SavedSearchListSerializer, s'il est utilisé dans les deux cas.

2023-09-28 15:35 UTC, cedricr commented on dora/services/templates/saved-search-notification.mjml
> +            <li>...</li>
```suggestion
            <li>…</li>
```

2023-10-02 12:45 UTC, AlexandreCantin commented on dora/orientations/templates/contact-beneficiary.mjml
> +    <mj-image src="{{ homepage_url }}/emails/illu-orientation.png" alt=""/>
C'est une image d'illustration qui ne comporte aucune information :)

2023-10-02 13:41 UTC, AlexandreCantin commented on dora/services/models.py
> +    frequency = models.ForeignKey(
Je trouvais que cette solution un peu plus de lisibilité… 🤷‍♂️

2023-10-02 14:04 UTC, cedricr commented on dora/services/models.py
> +    frequency = models.ForeignKey(
disons que le code devient plus simple avec des entiers, et que c'est plus facilement evolutif (on pourra rajouter les intervales qu'on veut sans migration de base de donnée). Mais bon, si ça te plait plus comme ça, laisse comme ça, ça ne sera pas trop compliqué à changer au besoin. C'est surtout dommage pour cette méthode je trouve https://github.com/gip-inclusion/dora-back/pull/173/files#diff-a7df6675129ffe1cae2f1807e0922cc129051444e6ae138292fe3c23eb2a2372R15

2023-10-02 14:55 UTC, AlexandreCantin commented on dora/services/management/commands/send_saved_searchs_notifications.py
> +                if datetime.fromisoformat(r["modification_date"]).date()
Hum… Non ce n'est pas une erreur, l'idée est d'avoir les services créés mais aussi ceux modifiés

Après le ticket parle du `nombre de services nouveaux ou modifiés` mais, en même temps, le courriel a comme titre `Il y a de nouveaux services correspondant à votre alerte`.
Je vais voir avec Andrei…

2023-10-02 15:40 UTC, cedricr commented on dora/services/management/commands/send_saved_searchs_notifications.py
> +                if datetime.fromisoformat(r["modification_date"]).date()
non on en avait parlé: la date de modification changer quand tu fais juste l'actualisation de tes services pas exemple, tu ne veux pas notifier les gens pour ça

2023-10-02 15:56 UTC, gestaltfabrik commented on dora/orientations/templates/contact-beneficiary.mjml
> +    <mj-image src="{{ homepage_url }}/emails/illu-orientation.png" alt=""/>
@AlexandreCantin @cedricr Oui, merci de les garder :) pour des raisons d'accessibilité mais aussi pour les fois où les images ne sont pas chargées par défaut/erreur de chargement.

2023-10-04 15:25 UTC, cedricr commented on dora/orientations/templates/contact-beneficiary.mjml
> +    <mj-image src="{{ homepage_url }}/emails/illu-orientation.png" alt=""/>
> Alors non, plutôt que de le répeter à chaque fois, tu gardes un email-base.mjml dans orientations/templates, qui va hériter du email-base.mjml de core/templates, en surchargeant seulement ça.

@AlexandreCantin tu n'as pas pris ce commentaire en compte.

2023-10-04 15:36 UTC, cedricr requested changes

2023-10-05 09:12 UTC, cedricr approved these changes
:tada: 

Ajoute un message dans le ticket Trello pour prévenir qu'il faudra retester (rapidement) les mails d'orientation.

2023-10-05 10:13 UTC, merged