Utilisation de pytest
gip-inclusion/dora-back pull request #185
Opened 2023-11-09 15:01 UTC by ikarius

https://trello.com/c/Ix6BKwGl/617-passer-%C3%A0-pytest

Première partie de la migration pytest.
Il y a plusieurs petites PR suivantes qui permettront : 
- d'augmenter la vitesse de traitement des tests : en parallélisant et réutilisant la base de test 
- de passer plus de tests au format pytest

Quelques remarques :
Certaines migrations injectent les données dans des tables de références : ça pose problème pour la réutilisation de la base (et l'augmentation du temps de test)
Si l'on réutilise la base de test (`-reuse-db`) certains tests ne passent carrément plus ou sont en erreur => une deuxième passe permettra d'adapter ces tests pour les faire passer.
Ces adaptations nécessiteront probablement l'utilisation de fixtures de données, qui pourront être utilisées / injectées dans les tests dans un mécanisme à définir (fixture ou mark).

2023-11-09 15:55 UTC, cedricr commented on config/settings.py
> +    DATABASES = {"default": dj_database_url.config(ssl_require=not DEBUG)}
Est-ce qu'on veut pas plutôt
```suggestion
    DATABASES = {"default": dj_database_url.config(ssl_require=(ENVIRONMENT != 'local'))}
```
?
Je peux imaginer faire tourner un test sur Scalingo avec DEBUG activé pour vérifier un truc, mais je veux quand même être en SSL dans ce cas.

2023-11-09 15:55 UTC, cedricr commented on dora/core/tests/test_structures_import.py
> +        self.assertEqual(Structure.objects.filter(siret=structure.siret).count(), 1)
Bien vu, je ne me souviens jamais duquel est "deprecated mais pas vraiment", et là le mélange des deux faisait mal aux yeux ;-)

2023-11-09 15:55 UTC, cedricr commented on dora/conftest.py
> +def baker(db):
L'idée c'est que sinon on ne peut pas utiliser directement `from model_bakery import baker` dans les tests, sinon la db risque de ne pas être utilisable? Mais est-ce que c'est nécessaire même avec le _use_db au-dessus? Sinon on est obligés de passer `baker` dans une bonne partie des signatures des tests; c'est pas le bout du monde, mais ça fait pas mal de bruit.

2023-11-09 15:55 UTC, cedricr commented on dora/conftest.py
> +def api_client():
Là j'imagine qu'il n'y pas vraiment d'alternative par contre…

2023-11-09 15:55 UTC, cedricr commented on dora/services/tests/test_logs.py
> +    # flaky ou intégration ?
tu ferais ça comment?

2023-11-09 16:28 UTC, ikarius commented on dora/core/tests/test_structures_import.py
> +        self.assertEqual(Structure.objects.filter(siret=structure.siret).count(), 1)
aucun mérite, pytest les trouve et t'avertit
j'ai mis du temps aussi et j'ai pas de moyen mnémotechnique

2023-11-09 16:29 UTC, ikarius commented on dora/conftest.py
> +def baker(db):
en fait je testais l'alternative, mais au final tu as raison sur l'ensemble des tests ce sera trop verbeux

2023-11-09 16:30 UTC, ikarius commented on dora/conftest.py
> +def api_client():
pour le coup, non :)

2023-11-09 16:33 UTC, ikarius commented on config/settings.py
> +    DATABASES = {"default": dj_database_url.config(ssl_require=not DEBUG)}
Si, bien sur

2023-11-09 17:44 UTC, cedricr commented on dora/services/tests/test_logs.py
> +    # flaky ou intégration ?
ah en fait, je teste pas le délai d'execution, je teste le fait que la date de création de l'objet nouvellement créé soit bien approximativement à maintenant. Mais c'est pas super élégant, je te l'accorde.

2023-11-09 17:50 UTC, cedricr commented on dora/conftest.py
> +def baker(db):
ouais et il faudrait qu'on fasse la même chose sur les make_service, etc, qui appellent baker en arrière plan.

2023-11-13 14:22 UTC, cedricr requested changes

2023-11-13 14:22 UTC, cedricr commented on dora/services/tests/test_logs.py
> +    # flaky ou intégration ?
le commentaire peut disparaitre du coup si tu as pas de meilleure idée?

2023-11-13 14:22 UTC, cedricr commented
Typiquement, le force push ici perd le lien sur le commits que j'ai déjà reviewés :sweat_smile: 
Là je suis parti du principe que tu as pas fait de trucs bizarre dans les vieux commit, et j'ai juste regardé le nouveau du coup.

2023-11-13 14:55 UTC, ikarius commented on dora/services/tests/test_logs.py
> +    # flaky ou intégration ?
je le vire, faute de meilleure idée immédiate. Si on refait un test du genre on pourra plancher dessus.

2023-11-13 15:00 UTC, cedricr approved these changes
:tada:

2023-11-13 16:07 UTC, merged