Envoi des notifications aux structures orphelines
gip-inclusion/dora-back pull request #196
Opened 2023-11-28 16:13 UTC by ikarius

DRAFT: en attente de certains élément à inclure à l'email et planification à déterminer

2023-12-01 14:32 UTC, cedricr commented on dora/structures/management/commands/send_orphan_structures_notifications.py
> +        orphan_structures = Structure.objects.exclude(email="").filter(members=None)
vérifier avec le metier si on exclut aussi celles qui ont des membres potentiels

2023-12-01 14:39 UTC, cedricr commented on dora/structures/management/commands/send_orphan_structures_notifications.py
> +        orphan_structures = orphan_structures.order_by("?")[:1]
un petit commentaire pour ne pas l'oublier, **ou** s'assurer que ça casse un test **ou** ajouter un parametre --limit à la commande (toujours pratique)

2023-12-04 17:12 UTC, ikarius commented on dora/structures/templates/notification-orphan-structure.mjml
> +<p>Nous vous invitons ainsi à rejoindre la structure <strong>{{ structure_name }}</strong> sur la plateforme afin de publier vos services en cliquant sur le bouton ci-dessous, ou en recopiant le lien
Je l'avais mis en version HTML et l'ai zappé en mjml. Merci !

2023-12-04 17:16 UTC, ikarius commented on dora/structures/templates/notification-orphan-structure.mjml
> +<p>Pour en savoir plus, vous pouvez visiter notre site et notre <a href="{{ dora_doc_link }}" target="_blank">documentation</a> ou bien vous inscrire à <a href="{{ webinar_link }}" target="_blank">un
Peut-être sur du webmail ? En y réflechissant, je suis tombé sur ça: https://www.badsender.com/en/2023/01/27/target-blank-links-email/
et je suis pas plus avancé :). Du pour, du contre.
Essayons de vivre en 2023 : je vire les `blank`

2023-12-04 17:22 UTC, ikarius commented on dora/structures/management/commands/send_orphan_structures_notifications.py
> +        orphan_structures = Structure.objects.exclude(email="").filter(members=None)
En cours avec Yoan, je modifie si besoin

2023-12-04 17:25 UTC, ikarius commented on dora/structures/templates/notification-orphan-structure.mjml
> +<p>Dans le cadre de notre démarche collective d’identification et activation de l’offre d’insertion nationale, nous avons identifié votre structure comme ayant vocation à figurer sur DORA afin de :</
J'avais pas vu le : après, c'est nécessaire dans ce cas ?

2023-12-04 17:26 UTC, ikarius commented on dora/structures/templates/notification-orphan-structure.mjml
> +    <li>réduire le temps passé à traiter vos demandes d'orientation</li>
mmm, la suggestion ne montre pas vraiment de différence. Tu veux dire sauter une ligne ?

2023-12-04 19:29 UTC, cedricr commented on dora/structures/templates/notification-orphan-structure.mjml
> +    <li>réduire le temps passé à traiter vos demandes d'orientation</li>
Pardon, apostrophe courbe, mais à force de changer de layout, je me suis raté ;-)

2023-12-11 14:02 UTC, cedricr approved these changes
Impeccable

2023-12-13 08:37 UTC, ikarius commented
Je mets juste le truc en attente, le temps que les notifications soit en place.
Si c'est le cas, la `management command` devrait disparaître, pour être remplacé par celle des notifications.

2023-12-21 18:02 UTC, ikarius commented
J'ai intégré : 
- le système de modification et supprimé l'ancienne management command devenue inutile.
- les données `mtm`

Certains tests ont été déplacés (structure du mail de notification), créés (queryset `Structure.objets.orphans`) et validés (tâche de notification).

Une fois la partie e-mail terminée, l'intégration est quasi-immédiate.

A relire à partir de : https://github.com/gip-inclusion/dora-back/pull/196/commits/7c0c8277be3b3739065b2ebe982f5985249828cb

2024-01-09 09:32 UTC, cedricr requested changes
mini correction à faire, et sinon ça m'a l'air tout bon!

2024-01-09 09:32 UTC, cedricr commented on dora/structures/tests/test_emails.py
> +    assert mail.outbox[0].to == [structure.email]
doublon

2024-01-09 11:08 UTC, ikarius commented on dora/structures/tests/test_emails.py
> +    assert mail.outbox[0].to == [structure.email]
ben oui, merci !

2024-01-09 11:14 UTC, cedricr approved these changes

2024-01-09 11:15 UTC, merged