[SQL] correctifs et amélioration des requêtes du tableau de bord "utilisateurs en souffrance"
gip-inclusion/dora-back pull request #201
Opened 2023-11-30 17:18 UTC by ikarius

https://trello.com/c/GTM7uLpc/993-tdb-des-invitations-utilisateurs-en-souffrance

Suite atelier / point 30.11.2023

2023-12-11 10:36 UTC, cedricr commented on queries/metabase/03-questions/0010_mb_members_invited.sql
> +    ss.invited_by_admin as "Invitation par un admin",
mais donc tu revois les questions metabase en conséquence? Ça me semble un peu bizarre que la vue s'appelle "members_invited" mais qu'en fait elle renvoie tout le monde

2023-12-11 10:36 UTC, cedricr commented on queries/metabase/03-questions/0020_q_members_invited_valid.sql
> +comment on view q_members_invited_valid is 'Liste des membres invités en attente de validation : e-mail validé';
le commentaire ne correspond plus a la requete il me semble; tu verifie que la personne a été invitée, mais pas que son email est valide. Et comme elle a été invitée, elle n'est pas en attente de validation :thinking:

2023-12-11 10:36 UTC, cedricr commented on queries/metabase/03-questions/0030_q_members_invited_invalid.sql
> +comment on view q_members_invited_invalid is 'Liste des membres invités en attente de validation : e-mail non validé';
pareil, je suis un peu paumé :rofl:

2023-12-11 10:36 UTC, cedricr commented on queries/metabase/03-questions/0040_q_orphan_users.sql
> +    and mu.id not in (select "ID utilisateur" from q_users_before_ic)
à rajouter dans le commentaire de tête peut-être?

2023-12-11 10:36 UTC, cedricr commented on queries/metabase/03-questions/0050_q_users_before_ic.sql
> +    -- aucune invitation en attente :
s'ils sont pas invited_by_admin, c'est pas des invitations

2023-12-13 08:38 UTC, ikarius commented on queries/metabase/03-questions/0050_q_users_before_ic.sql
> +    -- aucune invitation en attente :
commentaire trompeur, à supprimer

2023-12-13 08:39 UTC, ikarius commented on queries/metabase/03-questions/0010_mb_members_invited.sql
> +    ss.invited_by_admin as "Invitation par un admin",
les questions MB sont synchro, c'est une modification a posteriori après des modifs "live" effectuées sur MB.

2023-12-13 08:40 UTC, ikarius commented on queries/metabase/03-questions/0020_q_members_invited_valid.sql
> +comment on view q_members_invited_valid is 'Liste des membres invités en attente de validation : e-mail validé';
Correct, je vais refaire une passe sur les commentaires

2023-12-14 12:05 UTC, ikarius commented on queries/metabase/03-questions/0020_q_members_invited_valid.sql
> +comment on view q_members_invited_valid is 'Liste des membres invités en attente de validation : e-mail validé';
C'est le terme "en attente de validation" qui est trompeur. Je reformule en "en attente de rattachement"

2023-12-14 12:09 UTC, ikarius commented on queries/metabase/03-questions/0010_mb_members_invited.sql
> +    ss.invited_by_admin as "Invitation par un admin",
mal nommé pour le coup: il s'agit des utilisateurs en attente de rattachement. C'est une "extension" de `structures_structureputativemember`

2023-12-14 12:42 UTC, cedricr requested changes

2023-12-14 12:42 UTC, cedricr commented on queries/metabase/03-questions/0010_mb_members_invited.sql
le nom du ficher ne reflete plus la table

2023-12-14 12:42 UTC, cedricr commented on queries/metabase/03-questions/0010_mb_members_invited.sql
> +comment on table mb_putative_members is 'Liste des membres invités en attente de validation';
c'est pas "liste des membres en attente de rattachement plutot"? Il n'y a pas de filtre sur l'état de validation, ici, et on n'a pas seulement les invités

2023-12-14 12:42 UTC, cedricr commented on queries/metabase/03-questions/0020_q_members_invited_valid.sql
"members_invited" plutot que "members_invited_valid" non? on ne teste pas la validité ici

2023-12-14 12:42 UTC, cedricr commented on queries/metabase/03-questions/0030_q_members_invited_invalid.sql
>  where "E-mail validé" and not "Invitation par un admin";
ils sont pas invités si tu as un not "invitation par un admin"

2023-12-14 15:48 UTC, cedricr approved these changes

2023-12-14 15:59 UTC, merged