Départements multiples pour les gestionnaires
gip-inclusion/dora-back pull request #240
Opened 2024-02-29 18:01 UTC by ikarius

https://trello.com/c/J2leGHTB/1068-un-gestionnaire-peut-g%C3%A9rer-plusieurs-d%C3%A9partements

### Partie backend

Modification du modèle utilisateur pour permettre la gestion de plusieurs départements.
Le champ `user.department` disparait au profit de `user.departments` (array de `CharField`)
Les modifications sont répercutées sur les vues.

_Note_ : manquent un peu de tests, et je dois fouiller dans les recoins pour vérifier les impacts mais déjà visionnable dans l'ensemble

2024-03-04 15:31 UTC, cedricr requested changes
Presque tout bon !

2024-03-04 15:31 UTC, cedricr commented on dora/support/views.py
> -        if user.is_manager:
il va manquer cette condition.

2024-03-04 15:51 UTC, cedricr commented on dora/users/migrations/0024_user_departments.py
> +        if managers := User.objects.exclude(department="").filter(is_manager=True):
il te manque `User = apps.get_model("users", "User")` avant, sinon tu utilises le modèle User courrant, ou le champ department n’existe plus

2024-03-05 10:11 UTC, ikarius commented on dora/support/views.py
> -        if user.is_manager:
à cette étape, `department` devrait être correct. On a éliminé les cas où ça pourrait poser problème avec les permissions, non ?

2024-03-05 10:13 UTC, ikarius commented
Je vais vérifier les impacts annexes sur Metabase, mais je pense que pour cette partie ça devrait le faire ...

2024-03-05 11:44 UTC, cedricr commented on dora/support/views.py
> -        if user.is_manager:
non, si tu es manager, et que tu fais une requete sans passer 'department' en parametre, tu vas récupérer l'ensemble des structures... et non pas seulement celles auxquelles tu as droit.

2024-03-05 12:50 UTC, ikarius commented on dora/support/views.py
> -        if user.is_manager:
j'avais pas idée qu'on ne puisse pas passer le paramètre. Merci

2024-03-11 16:01 UTC, ikarius commented on dora/support/views.py
> +                assert user.departments
nit: bien que je les apprécie particulièrement dans d'autres langages, je me méfie des `asserts` en Python (option `-O` pour les désactiver)

2024-03-11 17:48 UTC, ikarius commented on dora/admin_express/views.py
> +        departments = [Department.objects.get_from_code(code) for code in q.split(",")]
Je me me demandais pourquoi pas une requête directe. Malin le petit cache.
Je m'aperçois ne pas avoir trop regardé cette zone ...
Mais l'ajout fonctionne nickel !

2024-03-12 09:29 UTC, cedricr commented on dora/admin_express/views.py
> +        departments = [Department.objects.get_from_code(code) for code in q.split(",")]
Oui on utilise tellement souvent ces modèles AdminExpress, c’était pas jouable de faire là requête à chaque fois. Dans le cas des départements et régions, il n'y a même qu’une seule requete de faite du coup.
Par contre ça devrait sans doute passer par le cache Redis, mais le code a été écrit avant que je le mette en place. Et en même temps, il y a des routes ou il y a tellement d’appels à ces méthodes, que les avoir en ram localement c’est pas mal non plus.

2024-03-12 14:02 UTC, merged