Comment avez-vous connu DORA ?
gip-inclusion/dora-back pull request #260
Opened 2024-03-28 16:58 UTC by ggounot

2024-04-02 07:12 UTC, ikarius commented on dora/users/models.py
> +
Assez d'accord d'une manière générale pour les `enums` quand il y a peu d'entrées et que ça change pas souvent.

2024-04-02 07:15 UTC, ikarius commented on dora/users/models.py
> +        verbose_name="Comment avez-vous connu DORA ?",
nit: la convention est de ne pas capitaliser les `verbose_name`, essentiellement pour l'affichage correct des filtres dans l'admin et que Django fait le taf automatiquement ailleurs.

2024-04-02 08:31 UTC, ikarius commented on dora/users/migrations/0026_user_discovery_method.py
> +    ]
Effectivement, comme discuté un petit coup de linting s'impose, je vais le mettre en place via CI

2024-04-02 09:08 UTC, ikarius commented on dora/users/models.py
> +
Par contre, plutôt que de le mettre dans le module `models.py`, par convention, on les regroupes souvent dans un module `enums.py` et sur la forme plus naturelle d'un `models.TextChoices`.

Tu as un exemple dans le package / app `services`.

2024-04-02 09:25 UTC, ikarius commented on dora/users/views.py
> +        if 'main_activity' not in attrs and not self.instance.main_activity:
`ruff` te préviendra, mais je le fais aussi :) Les simples quotes sont peut utilisés et le linter les considèrent comme un warning (il y en a ailleurs dans le code).

2024-04-02 09:33 UTC, ikarius commented on dora/users/views.py
> +        return attrs
2 nits:
- `attrs.get("main_activity")` pourrait simplifier un peu le code
- le `validate()` global des sérialiseurs est utile si on fait des validations qui font appels à plusieurs attributs. Vu que tu n'utilse que `main_activity`, un `validate_main_activity` est plus ciblé (et executé avant le validate global).

2024-04-02 09:41 UTC, ikarius commented on dora/users/views.py
> +    serializer = UserProfileSerializer(request.user, data=request.data, partial=True)
N'ayant pas regardé la partie front encore, partial pour cause de PATCH ?

2024-04-02 09:43 UTC, ikarius requested changes
Juste quelques remarques en nit, à toi de voir.
Par contre, un petit coup de `ruff` serait pas de trop (il me sort une vingtaine d'utilisation du simple quote) :)

2024-04-02 09:55 UTC, ggounot commented on dora/users/models.py
> +        verbose_name="Comment avez-vous connu DORA ?",
Pourtant les autres champs `verbose_name` sont bien capitalisés.

Qu'attends-tu ? _comment avez-vous connu DORA ?_ ou _comment avez-vous connu dora ?_ ?

2024-04-02 09:57 UTC, ggounot commented on dora/users/views.py
> +        return attrs
J'ai utilisé `validate()` car je voulais que le champ `main_activity` soit facultatif si il est déjà renseigné. Si j'utilise `validate_main_activity()`, la vérification de son existence ne se fait pas s'il n'est pas fourni.

2024-04-02 09:59 UTC, ggounot commented on dora/users/views.py
> +    serializer = UserProfileSerializer(request.user, data=request.data, partial=True)
Mon but est de rendre possible la mise à jour partielle des données. Effectivement je pourrais aller plus loin dans le _restful_ en mettant PATCH plutôt que POST.

2024-04-02 10:24 UTC, ikarius commented on dora/users/models.py
> +        verbose_name="Comment avez-vous connu DORA ?",
yep, exactement.
Les autres champs le sont et c'est une erreur (mineure) : à l'occase on pourra les repasser en minuscule.
Souci : la modification du `verbose_name` entraîne une migration, c'est pour ça que je laisse couler.
La technique de filou consiste à modifier directement la migration en compagnie du modèle pour tromper Django.

2024-04-02 10:25 UTC, ikarius commented on dora/users/views.py
> +    serializer = UserProfileSerializer(request.user, data=request.data, partial=True)
Dans ce cas oui ! Sinon l'ORM est malin ...

2024-04-02 14:07 UTC, ggounot commented on dora/users/models.py
> +
Fait dans 60ffc837eb187c85a098af804e2c57a1e63c449a

2024-04-02 14:08 UTC, ggounot commented on dora/users/migrations/0026_user_discovery_method.py
> +    ]
Fait dans 2f3f1fb8cd83bb0785bbab1b3d3bfd6b9a5e9d55. Bizarrement le hook de pré-commit ne s'est pas exécuté chez moi.

2024-04-02 14:09 UTC, ggounot commented on dora/users/views.py
> +        if 'main_activity' not in attrs and not self.instance.main_activity:
Corrigé dans 2f3f1fb8cd83bb0785bbab1b3d3bfd6b9a5e9d55. Bizarrement le hook de pré-commit ne s'est pas exécuté chez moi.

2024-04-02 14:28 UTC, ikarius approved these changes

2024-04-02 15:44 UTC, ggounot commented on dora/users/migrations/0026_user_discovery_method.py
> +    ]
Fait dans 43315c223015e32f2959e8b25004dfe9c2409236

2024-04-02 15:45 UTC, ggounot commented on dora/users/models.py
> +        verbose_name="Comment avez-vous connu DORA ?",
Fait dans 43315c223015e32f2959e8b25004dfe9c2409236

2024-04-02 15:55 UTC, ggounot commented on dora/users/views.py
> +    serializer = UserProfileSerializer(request.user, data=request.data, partial=True)
J'ai ajouté la méthode PATCH dans 4040de12133833b591e65ec0ad0b04fc066538ef.

Je ne comprends pas ce que tu veux dire avec « Sinon l'ORM est malin ... »

2024-04-03 12:30 UTC, ggounot commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter à l'onboarding / inscription la question de "ou avez vous connnu DORA ?"](https://trello.com/c/cQL0egkb/921-ajouter-%C3%A0-lonboarding-inscription-la-question-de-ou-avez-vous-connnu-dora)

2024-04-04 08:10 UTC, ikarius submitted a review, later dismissed
LGTM

2024-04-15 15:20 UTC, ikarius approved these changes
Déjà approuvé, je débloque l'autosquash. de ton coté ferme les discussions de la partie front (tout est validé).

2024-04-15 15:20 UTC, merged