Modification des e-mails envoyés lors de la création d'une orientation
gip-inclusion/dora-back pull request #300
Opened 2024-05-30 09:01 UTC by ikarius

Les informations personnelles ont été réduites au minimum dans le
contenu des e-mails envoyés lors de la création d'une orientation
(AIPD).

2024-05-30 13:12 UTC, ggounot requested changes

2024-05-30 13:12 UTC, ggounot commented on dora/orientations/templates/orientation-created-structure.mjml
> +    vous a adressé un bénéficiaire pour le service {% include "partials/service-link.html" %}.
Le texte dans Notion indique _**votre** service_. Mais _**le** service_ me semble plus approprié.

2024-05-30 13:12 UTC, ggounot commented on dora/orientations/templates/orientation-created-beneficiary.mjml
> +  <p><strong>Pour des questions concernant cette demande, veuillez contactez le prescripteur ou prescriptrice :</strong></p>
C'est bien le texte du Notion mais on devrait écrire _veuillez contact**er**_. Ne devrions-nous pas écrire _**la** prescriptrice_. ?

2024-05-30 13:12 UTC, ggounot commented on dora/orientations/templates/orientation-created-beneficiary.mjml
>      {% include "partials/structure-link.html" %}
Le lien ne fonctionne pas chez moi.

2024-05-30 13:12 UTC, ggounot commented on dora/orientations/templates/orientation-created-beneficiary.mjml
>    </ul>
Si le bloc au-dessus n'est pas affiché, ces infos de contact sont affichées en-dessous de _veuillez contactez le prescripteur ou prescriptrice_. Or ce sont les infos de contact du référent.

2024-05-30 13:12 UTC, ggounot commented on dora/orientations/templates/orientation-created-referent.mjml
>    {{ data.get_beneficiary_full_name }} a été orienté·e vers {{ data.get_service_name }}
Le texte dans Notion est différent pour cette ligne.

2024-05-30 15:04 UTC, ikarius commented on dora/orientations/templates/orientation-created-referent.mjml
>    {{ data.get_beneficiary_full_name }} a été orienté·e vers {{ data.get_service_name }}
de mémoire, il n'est envoyé que si le prescripteur n'est pas le référent. Je regarde ...

2024-05-30 15:06 UTC, ikarius commented on dora/orientations/templates/orientation-created-prescriber.mjml
>      {% include "partials/structure-link.html" %}
ah, il fonctionne ici.
Works on my machine: à creuser ..

2024-05-30 15:09 UTC, ikarius commented on dora/orientations/templates/orientation-created-structure.mjml
> +    vous a adressé un bénéficiaire pour le service {% include "partials/service-link.html" %}.
Oui, on n'est pas à la virgule près :)

2024-05-30 15:11 UTC, ikarius commented on dora/orientations/templates/orientation-created-beneficiary.mjml
> +  <p><strong>Pour des questions concernant cette demande, veuillez contactez le prescripteur ou prescriptrice :</strong></p>
exact, faute qui est passé au travers.
et oui pour la prescriptrice, c'est d'ailleurs le cas dans un autre template.

2024-05-30 15:12 UTC, ikarius commented on dora/orientations/templates/orientation-created-beneficiary.mjml
> +  <p><strong>Pour des questions concernant cette demande, veuillez contactez le prescripteur ou prescriptrice :</strong></p>
et un espace insécable en plus

2024-05-30 15:13 UTC, ikarius commented on dora/orientations/templates/orientation-created-beneficiary.mjml
>      {% include "partials/structure-link.html" %}
idem fonctionne ici (sur un service d·i)

2024-05-30 15:14 UTC, ikarius commented on dora/orientations/templates/orientation-created-beneficiary.mjml
>      {% include "partials/structure-link.html" %}
j'essaye sur un autre type de service ...

2024-05-30 16:01 UTC, ikarius commented on dora/orientations/templates/orientation-created-beneficiary.mjml
>    </ul>
oui, c'est l'idée si prescripteur est référent

2024-05-30 16:10 UTC, ikarius commented on dora/orientations/templates/orientation-created-beneficiary.mjml
>      {% include "partials/structure-link.html" %}
Bizarre j'ai pas vraiment touché cette partie, ça doit dater ...

2024-05-30 16:16 UTC, ikarius commented on dora/orientations/templates/orientation-created-prescriber.mjml
>      {% include "partials/structure-link.html" %}
Idem ci-dessus, je soupçonne un bug plus ancien ...

2024-05-30 16:20 UTC, ikarius commented on dora/orientations/templates/orientation-created-prescriber.mjml
>      {% include "partials/structure-link.html" %}
bingo, bug corrigé. Bon œil !

2024-05-30 16:35 UTC, ikarius commented on dora/orientations/templates/orientation-created-beneficiary.mjml
>      {% include "partials/structure-link.html" %}
Effectivement vieux bug, présent dans les précédentes versions.

2024-06-01 13:40 UTC, ggounot commented on dora/orientations/templates/orientation-created-referent.mjml
> +  <p>Pour toute question concernant le traitement de la demande, veuillez contacter le référent du service&nbsp;:</p>
Cette ligne doit être en gras

2024-06-01 13:40 UTC, ggounot commented on dora/orientations/templates/orientation-created-beneficiary.mjml
>      {% include "partials/structure-link.html" %}
Cool qu'il soit corrigé maintenant :)

2024-06-01 15:27 UTC, ikarius commented on dora/orientations/templates/orientation-created-referent.mjml
> +  <p>Pour toute question concernant le traitement de la demande, veuillez contacter le référent du service&nbsp;:</p>
t'as de meilleurs yeux que moi. Tu me diras, c'est pas difficile ...

2024-06-03 08:00 UTC, ggounot approved these changes

2024-06-03 08:01 UTC, merged