Ajouts de profils Django
gip-inclusion/dora-back pull request #312
Opened 2024-06-22 09:59 UTC by ikarius

2024-06-24 12:43 UTC, cedricr reviewed
Revue intermédiaire
- en dehors des fichiers de config ça a l’air bon pour moi
- gros doute sur le SECRET_KEY

2024-06-24 12:43 UTC, cedricr commented on config/settings/base.py
> +DJANGO_SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]
Hum, SECRET_KEY c’est un settings 'officiel' de django, tu ne peux pas le renommer
https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/#secret-key

2024-06-25 16:28 UTC, ggounot requested changes
Super ! Excellent travail de refactoring. Les différences de settings seront tout de suite plus claires.

Quelques commentaires ainsi que :
- `IS_TESTING = False` n’est plus utilisé du tout ?
- `DJANGO_DEBUG=true` peut être supprimé de env-example/dev.env vu qu’il n’est plus utilisé

2024-06-25 16:28 UTC, ggounot commented on config/settings/dev.py
> +if DATABASE_URL := os.environ.get("DATABASE_URL"):
DATABASE_URL est déjà défini via la variable d'environnement dans `base.py`.

```suggestion
if DATABASE_URL:
```

Comme tu as fait dans `prod.py`.

2024-06-25 16:28 UTC, ggounot commented on config/settings/dev.py
> +AUTH_PASSWORD_VALIDATORS = []
Pourquoi est-il vidé ici ?

2024-06-26 08:04 UTC, ikarius commented on config/settings/dev.py
> +ALLOWED_HOSTS = ["localhost", "127.0.0.1", "192.168.0.1", "0.0.0.0"]
On pourrait faire double : prendre la valeur d'une var-env (splitté), et mettre ça en défaut si jamais absente

2024-06-26 08:05 UTC, ikarius commented on config/settings/dev.py
> +    "whitenoise.middleware.WhiteNoiseMiddleware",
Et oui, avoir plusieurs paires d'yeux à disposition est une bonne chose ! Merci !

2024-06-26 08:05 UTC, ikarius commented on config/settings/dev.py
> +AUTH_PASSWORD_VALIDATORS = []
pas forcément utile pour un env de dev

2024-06-26 13:52 UTC, ikarius commented
> Suite à une vérifications manuelle, j'ai quelques remarques/questions ainsi que les deux suivantes :
> 
>     * `IS_TESTING = False` n’est plus utilisé du tout ?
> 

Nope. C'est d'ailleurs une des raisons de l'existence du profil `test`

>     * `DJANGO_DEBUG=true` peut être supprimé de env-example/dev.env vu qu’il n’est plus utilisé

Exact !

2024-06-26 14:50 UTC, ggounot requested changes
Juste une petite remarque sur `LOGGING`

Du reste, j'ai fait les diffs de settings et ça me semble correct.

2024-06-26 14:50 UTC, ggounot commented on config/settings/dev.py
> +}
Les valeurs de LOGGING déclarées dans base.py sont écrasées et on perd notamment la configuration de `dora.logs.core`.

J'imagine que tu veux juste faire ça :

`LOGGING["loggers"]["django"]["level"] = os.getenv("DJANGO_LOG_LEVEL", "INFO")`

2024-06-26 15:09 UTC, ikarius commented on config/settings/dev.py
> +}
c'est bien ça, merci !

2024-06-26 15:14 UTC, ggounot commented on config/settings/dev.py
> +}
Top

2024-06-26 15:14 UTC, ggounot approved these changes
C'est bon pour moi !

2024-06-26 15:15 UTC, merged